# Generated by Django 4.2.1 on 2023-06-04 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('CAR', 'Car Theft Insurance'), ('PROPERTY', 'Property Insurance'), ('MED', 'Medical Insurance'), ('GEN', 'General Insurance')], default='GEN', max_length=20)),
                ('minimal_cost', models.IntegerField()),
                ('duration', models.DurationField()),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('TRANSPORT', 'Transport'), ('BUILDING', 'Building'), ('PERSON', 'Person')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateTimeField(auto_now=True)),
                ('cost', models.CharField(max_length=60)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.insurance')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.object')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.office'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
