# Generated by Django 4.2.1 on 2023-06-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.object'),
        ),
    ]
