# Generated by Django 4.2.1 on 2023-06-05 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_alter_contract_sign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.agent'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('OUTDATED', 'Outdated')], default='PENDING', max_length=15, null=True),
        ),
    ]
